name: proyecto_jandula
description: Aplicación para simular la función de Séneca en el centro
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+4
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.0.4
  firebase_admob: ^0.9.3+1
  animator: ^1.0.0+5
  cloud_firestore: ^0.13.4+2
  flip_card: ^0.4.4
  pdf: ^1.3.24
  geolocator: ^5.3.1
  android_intent: ^0.3.6+1
  location: ^3.0.2
  firebase_database: ^3.1.3
  awesome_dialog: ^0.1.3
  intl: ^0.16.1
  flutter_share: ^1.0.2+1
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.5.1
  printing: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/